version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_MAPS_KEY: ${NEXT_PUBLIC_MAPS_KEY}
        NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
        AUTH_SECRET: ${AUTH_SECRET}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-${AUTH_SECRET}}
        AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
        AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST:-true}
        NODE_ENV: ${NODE_ENV:-production}
    working_dir: /app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    image: beyonds-cloud
    environment:
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_MAPS_KEY=${NEXT_PUBLIC_MAPS_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-${AUTH_SECRET}}
      - AUTH_DISCORD_ID=${AUTH_DISCORD_ID}
      - AUTH_DISCORD_SECRET=${AUTH_DISCORD_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST:-true}
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    restart: unless-stopped
